image: Visual Studio 2019

shallow_clone: true

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

only_commits:
  files:
    - src/
    - vc14/
    - appveyor.yml

install:
  - cmd: vcpkg install

build:
  parallel: true

cache:
  - c:\tools\vcpkg\installed\

after_build:
  - 7z a -tzip tfs-win-%PLATFORM%-%CONFIGURATION%.zip -r %APPVEYOR_BUILD_FOLDER%\vc14\%PLATFORM%\%CONFIGURATION%\*.dll %APPVEYOR_BUILD_FOLDER%\vc14\%PLATFORM%\%CONFIGURATION%\theforgottenserver*.exe %APPVEYOR_BUILD_FOLDER%\data %APPVEYOR_BUILD_FOLDER%\config.lua.dist %APPVEYOR_BUILD_FOLDER%\key.pem %APPVEYOR_BUILD_FOLDER%\LICENSE %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\schema.sql

artifacts:
  - path: vc14\%PLATFORM%\%CONFIGURATION%\theforgottenserver*.exe
  - path: vc14\%PLATFORM%\%CONFIGURATION%\*.dll
  - path: tfs-win-%PLATFORM%-%CONFIGURATION%.zip
